#!/bin/bash
set -eu -o pipefail

flags=()

# auto-detect platform
if [ -e /usr/bin/raspinfo ]
then
  flags+=(-f interface/raspberrypi-swd.cfg)
else
  flags+=(-f interface/cmsis-dap.cfg)
fi

flags+=(-f target/rp2040.cfg)
flags+=(-c "adapter speed 20000")

exec openocd "${flags[@]}" "$@"
